server:
  port: 8090
spring:
  rabbitmq:
    host:  192.168.152.1
    port: 5672
    username: test
    password: root
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 手动ACT 消费者使用
    publisher-confirm-type: simple # 生产者开启confirm机制
    publisher-returns: false # 生产者开启return机制
redis:
  host: 192.168.152.1